In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [27]:
X = []
Y = []
X_pred = []

rows = int(input("Enter what is the total number of records in the dataset : "))
columns = int(input("Enter the number of columns : "))

for i in range (rows):
    a = []
    for j in range (columns):
        a.append(float(input("Enter "+str(j)+"th value for "+str(i)+"th row: ")))
    X.append(a)

for i in range (rows):
    Y.append(float(input("Enter the "+str(i)+"th value for y array")))
    


Enter what is the total number of records in the dataset : 4
Enter the number of columns : 3
Enter 0th value for 0th row: 10
Enter 1th value for 0th row: 2
Enter 2th value for 0th row: 3
Enter 0th value for 1th row: 31
Enter 1th value for 1th row: 4
Enter 2th value for 1th row: 5
Enter 0th value for 2th row: 15
Enter 1th value for 2th row: 6
Enter 2th value for 2th row: 7
Enter 0th value for 3th row: 3
Enter 1th value for 3th row: 9
Enter 2th value for 3th row: 10
Enter the 0th value for y array11
Enter the 1th value for y array12
Enter the 2th value for y array11
Enter the 3th value for y array12


In [28]:
X = np.array(X)
r=np.size(X,0)
train = round(0.8*r)
test = r - round(0.8*r)

In [29]:
y = np.array(Y)
y

array([11., 12., 11., 12.])

In [30]:
X_train = X[:train,:]
X_train

array([[10.,  2.,  3.],
       [31.,  4.,  5.],
       [15.,  6.,  7.]])

In [31]:
y_train = y[:train]
y_train

array([11., 12., 11.])

In [32]:
X_test = X[train:,:]
y_test = y[train:]

In [38]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
#regressor.fit(X_train, y_train)
regressor.fit(X, y)

LinearRegression()

In [34]:
#Intercept for the given dataset

In [35]:
regressor.intercept_

10.628378378378379

In [36]:
#Coeffecients of Regression

In [39]:
regressor.coef_

array([0.0269601 , 0.07129542, 0.07129542])

In [ ]:
from sklearn.metrics import mean_squared_error
import re
def main(): 
    y_true = []
    y_pred = []
    i_true = re.sub(r"[\([{})\]]", "", input())
    i_pred = re.sub(r"[\([{})\]]", "", input())
    l_true = list(i_true.split(','))
    l_pred = list(i_pred.split(','))
    for a in l_true:
        y_true.append(float(a))
    for a in l_pred:
        y_pred.append(float(a))
    
    mse1 = mean_sq_err(y_true,y_pred)
    mse2 = mean_squared_error(y_true, y_pred)
    
    if mse1==mse2:
        print(mse1)
    
def mean_sq_err(y_t, y_p):
    if len(y_t)==len(y_p):
        s = 0
        for j in range (len(y_t)):
            e_s = (y_t[j]-y_p[j])**2
            s = s + e_s
        return(s/len(y_p))
    
    
def MeanSquaredError(y_true,y_pred):
    result = mean_squared_error(y_true, y_pred)
    return result    
    
    
if __name__ == "__main__":
    main()

[4,5,7,12]
